# Introduction


**NumPy provides a foundation for handling multi-dimensional arrays and matrices, enabling efficient mathematical operations.**


#### What is NumPy?

- NumPy stands for Numerical Python.
- It is a Python library used for working with arrays and It was created in 2005 by Travis Oliphant.
- It is an open source project and you can use it freely.
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.

#### Why NumPy is important:

- Speed and Efficiency: NumPy's arrays are faster and use less memory than Python lists.
- Broad Functionality: It offers tools for mathematical, logical, and statistical operations.
- Seamless Integration: Works well with libraries like Pandas, Matplotlib, and SciPy.
- Key Concept: Arrays

> n array in NumPy is a grid of values, all of the same type, indexed by a tuple of non-negative integers.

#### Why Use NumPy?

- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.-

> Data Science: is a branch of computer science where we study how to store, use and analyze data for deriving information from it.


#### Why is NumPy Faster Than Lists?

- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

- This behavior is called locality of reference in computer science.

- This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

#### Which Language is NumPy written in?

- NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

# Getting Started

#### Installation of NumPy

- If you have Python and PIP already installed on a system, then installation of NumPy is very easy.
- Install it using this command in command terminal:

> pip install numpy

#### Import NumPy

- Once NumPy is installed, import it in your applications by adding the import keyword:

> import numpy

In [5]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


#### NumPy as np

- NumPy is usually imported under the np alias.

- alias: In Python alias are an alternate name for referring to the same thing.

- Create an alias with the as keyword while importing:

> import numpy as np

- Now the NumPy package can be referred to as np instead of numpy.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


#### Checking NumPy Version

- The version string is stored under __version__ attribute.

In [4]:
print(np.__version__)

2.1.3


# Creating Arrays

#### Create a NumPy ndarray Object

- NumPy is used to work with arrays. The array object in NumPy is called ndarray.
- ndarray is nothing but a array object in numpy.
- We can create a NumPy ndarray object by using the array() function.

In [7]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


> We already imported **numpy** library as **np** don't need to import everytime.

> type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.

> To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [8]:
#Use a tuple to create a NumPy array:

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [9]:
#Use a list to create a NumPy array:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [10]:
#with dict how?
arr = np.array({1:44, 2:32, 3:34, 4:33, 5:33})

print(arr)

{1: 44, 2: 32, 3: 34, 4: 33, 5: 33}


### Dimensions in Arrays

- A dimension in arrays is one level of array depth (nested arrays).

- nested array: are arrays that have arrays as their elements.m

#### 0-D Arrays

- 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [12]:
#Create a 0-D array with value 

arr = np.array(42)

print(arr)

42


#### 1-D Arrays

- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

- These are the most common and basic arrays.

In [13]:
#Create a 1-D array containing the values 1,2,3,4,5:

arr = np.array([1, 2, 3, 4])

print(arr.shape)
print(arr)

(4,)
[1 2 3 4]


#### 2-D Arrays

- An array that has 1-D arrays as its elements is called a 2-D array.

- These are often used to represent matrix or 2nd order tensors.

> NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

In [14]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

arr = np.array([[1, 2, 3,6], [4, 5, 8, 6],[1, 2, 3,6]])

print("Shape of 3D arrar(row,column,no. of element):",arr.shape)
print()

print(arr)

Shape of 3D arrar(row,column,no. of element): (3, 4)

[[1 2 3 6]
 [4 5 8 6]
 [1 2 3 6]]


#### 3-D arrays

- An array that has 2-D arrays (matrices) as its elements is called 3-D array.

- These are often used to represent a 3rd order tensor.

In [15]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

arr = np.array([[[1, 2, 3], [4, 5, 6],[9,8,7]], 
                [[1, 2, 3], [4, 5, 6],[9,4,5]]])

print("Shape of 3D arrar(row,column,no. of element):",arr.shape)
print()
print(arr)

Shape of 3D arrar(row,column,no. of element): (2, 3, 3)

[[[1 2 3]
  [4 5 6]
  [9 8 7]]

 [[1 2 3]
  [4 5 6]
  [9 4 5]]]


#### Check Number of Dimensions?

- NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [16]:
#Check how many dimensions the arrays have:

a = np.array(42)

b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]], 
              [[1, 2, 3], [4, 5, 6]]
             ])


e = np.array([ [ [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]] ],
               [ [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]] ]
             ])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
4


#### Higher Dimensional Arrays

- An array can have any number of dimensions.

- When the array is created, you can define the number of dimensions by using the ndmin argument.

In [17]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


> In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.