### About Numpy :

> NumPy is a Python library.

> NumPy is used for working with arrays.

> NumPy is short for "Numerical Python".

# NumPy Introduction


#### What is NumPy?

- NumPy is a Python library used for working with arrays.

- It also has functions for working in domain of linear algebra, fourier transform, and matrices.

- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

- NumPy stands for Numerical Python.

#### Why Use NumPy?



- In Python we have lists that serve the purpose of arrays, but they are slow to process.

- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

- Arrays are very frequently used in data science, where speed and resources are very important.

> Data Science: is a branch of computer science where we study how to store, use and analyze data for deriving information from it.

#### Why is NumPy Faster Than Lists?

- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

- This behavior is called locality of reference in computer science.

- This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

#### Which Language is NumPy written in?

- NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

# NumPy Getting Started


#### Installation of NumPy

- If you have Python and PIP already installed on a system, then installation of NumPy is very easy.

- Install it using this command in command terminal:

> pip install numpy

#### Import NumPy

- Once NumPy is installed, import it in your applications by adding the import keyword:

> import numpy

In [2]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


#### NumPy as np

- NumPy is usually imported under the np alias.

- alias: In Python alias are an alternate name for referring to the same thing.

- Create an alias with the as keyword while importing:

> import numpy as np

- Now the NumPy package can be referred to as np instead of numpy.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


#### Checking NumPy Version

- The version string is stored under __version__ attribute.

In [6]:
print(np.__version__)

2.1.3


# NumPy Creating Arrays


#### Create a NumPy ndarray Object

- NumPy is used to work with arrays. The array object in NumPy is called ndarray.
- We can create a NumPy ndarray object by using the array() function.

In [8]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


> We already imported **numpy** library as **np** don't need to import everytime.

> type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.

> To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [9]:
#Use a tuple to create a NumPy array:

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [10]:
#Use a list to create a NumPy array:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### Dimensions in Arrays

- A dimension in arrays is one level of array depth (nested arrays).

- nested array: are arrays that have arrays as their elements.

#### 0-D Arrays

- 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.



In [13]:
#Create a 0-D array with value 

arr = np.array(42)

print(arr)

42


#### 1-D Arrays

- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

- These are the most common and basic arrays.

In [14]:
#Create a 1-D array containing the values 1,2,3,4,5:

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


#### 2-D Arrays

- An array that has 1-D arrays as its elements is called a 2-D array.

- These are often used to represent matrix or 2nd order tensors.

> NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

In [17]:
#Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


#### 3-D arrays

- An array that has 2-D arrays (matrices) as its elements is called 3-D array.

- These are often used to represent a 3rd order tensor.

In [19]:
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#### Check Number of Dimensions?

- NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
#Check how many dimensions the arrays have:

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

#### Higher Dimensional Arrays

- An array can have any number of dimensions.

- When the array is created, you can define the number of dimensions by using the ndmin argument.

In [21]:
#Create an array with 5 dimensions and verify that it has 5 dimensions:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


> In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

#  NumPy Array Indexing

#### Access Array Elements

- Array indexing is the same as accessing an array element.

- You can access an array element by referring to its index number.

- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [22]:
#Get the first element from the following array:

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [23]:
#Get the second element from the following array.

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [24]:
#Get third and fourth elements from the following array and add them.

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


##### Access 2-D Arrays

- To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

- Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [25]:
#Access the element on the first row, second column:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [26]:
#Access the element on the 2nd row, 5th column:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


#### Access 3-D Arrays

- To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [27]:
#Access the third element of the second array of the first array:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


#### Example Explained

arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:

[[1, 2, 3], [4, 5, 6]]

**and:**

[[7, 8, 9], [10, 11, 12]]

Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:

[1, 2, 3]

**and:**

[4, 5, 6]

Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6

Since we selected 2, we end up with the third value:
6

#### Negative Indexing

Use negative indexing to access an array from the end.

In [28]:
#Print the last element from the 2nd dim:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [30]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr[1, 1, 0])

7


# NumPy Array Slicing

#### Slicing arrays

- Slicing in python means taking elements from one given index to another given index.

- We pass slice instead of index like this: [start:end].

- We can also define the step, like this: [start:end:step].

- If we don't pass start its considered 0

- If we don't pass end its considered length of array in that dimension

- If we don't pass step its considered 1

In [31]:
#Slice elements from index 1 to index 5 from the following array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


[2 3 4 5]


> Note: The result includes the start index, but excludes the end index.

In [32]:
#Slice elements from index 4 to the end of the array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [33]:
#Slice elements from the beginning to index 4 (not included):

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


#### Negative Slicing

- Use the minus operator to refer to an index from the end:

In [34]:
#Slice from the index 3 from the end to index 1 from the end:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


#### STEP

- Use the step value to determine the step of the slicing:

In [36]:
#Return every other element from index 1 to index 5:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [37]:
#Return every other element from the entire array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])


[1 3 5 7]


#### Slicing 2-D Arrays

In [38]:
#From the second element, slice elements from index 1 to index 4 (not included):

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


> Note: Remember that second element has index 1.

In [39]:
#From both elements, return index 2:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [40]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:2])

[1 2]


# NumPy Data Types


#### Data Types in Python

- By default Python have these data types:

1. strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
2. integer - used to represent integer numbers. e.g. -1, -2, -3
3. float - used to represent real numbers. e.g. 1.2, 42.42
4. boolean - used to represent True or False.
5. complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

#### Data Types in NumPy

- NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

- Below is a list of all data types in NumPy and the characters used to represent them.

> i - integer

> b - boolean

> u - unsigned integer

> f - float

> c - complex float

> m - timedelta

> M - datetime

> O - object

> S - string

> U - unicode string

> V - fixed chunk of memory for other type ( void )

#### Checking the Data Type of an Array

- The NumPy array object has a property called dtype that returns the data type of the array:

In [42]:
#Get the data type of an array object:

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [43]:
#Get the data type of an array containing strings:

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


#### Creating Arrays With a Defined Data Type

- We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [46]:
#Create an array with data type string:

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


> For i, u, f, S and U we can define size as well.

In [47]:
#Create an array with data type 4 bytes integer:

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


#### What if a Value Can Not Be Converted?

- If a type is given in which elements can't be casted then NumPy will raise a ValueError.

> ValueError: In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

In [49]:
#A non integer string like 'a' can not be converted to integer (will raise an error):

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

#### Converting Data Type on Existing Arrays

- The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

- The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

- The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [50]:
#Change data type from float to integer by using 'i' as parameter value:

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [51]:
#Change data type from float to integer by using int as parameter value:

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [52]:
#Change data type from integer to boolean:

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [53]:
arr = np.array([-1, 0, 1])
newarr = arr.astype(bool)
print(newarr)

[ True False  True]


# NumPy Array Copy vs View


#### The Difference Between Copy and View

- The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

- The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

- The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.


#### COPY:


In [56]:
#Make a copy, change the original array, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


> The copy SHOULD NOT be affected by the changes made to the original array.



#### VIEW:

In [57]:
#Make a view, change the original array, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


> The view SHOULD be affected by the changes made to the original array.

#### Make Changes in the VIEW:

In [58]:
#Make a view, change the view, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


> The original array SHOULD be affected by the changes made to the view.

#### Check if Array Owns its Data

- As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

- Every NumPy array has the attribute base that returns None if the array owns the data.

- Otherwise, the base  attribute refers to the original object.

In [59]:
#Print the value of the base attribute to check if an array owns it's data or not:

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


- The copy returns None.
- The view returns the original array.

In [60]:
original_array = np.array([1, 2, 3])
x = original_array.copy()
x[0] = 5
print(original_array)

[1 2 3]


# NumPy Array Shape

#### Shape of an Array

- The shape of an array is the number of elements in each dimension.

#### Get the Shape of an Array

- NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [62]:
#Print the shape of a 2-D array:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


> The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

In [63]:
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


#### What does the shape tuple represent?

- Integers at every index tells about the number of elements the corresponding dimension has.

- In the example above at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.

In [64]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


# NumPy Array Reshaping


#### Reshaping arrays

- Reshaping means changing the shape of an array.

- The shape of an array is the number of elements in each dimension.

- By reshaping we can add or remove dimensions or change number of elements in each dimension.

#### Reshape From 1-D to 2-D

- Convert the following 1-D array with 12 elements into a 2-D array.

In [66]:
#The outermost dimension will have 4 arrays, each with 3 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### Reshape From 1-D to 3-D

- Convert the following 1-D array with 12 elements into a 3-D array.



In [67]:
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### Can We Reshape Into any Shape?

- Yes, as long as the elements required for reshaping are equal in both shapes.

- We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [68]:
#Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)


ValueError: cannot reshape array of size 8 into shape (3,3)

#### Returns Copy or View?


In [70]:
#Check if the returned array is a copy or a view:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


> The example above returns the original array, so it is a view.

#### Unknown Dimension

- You are allowed to have one "unknown" dimension.

- Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

- Pass -1 as the value, and NumPy will calculate this number for you.

In [72]:
#Convert 1D array with 8 elements to 3D array with 2x2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


> Note: We can not pass -1 to more than one dimension.



#### Flattening the arrays

- Flattening array means converting a multidimensional array into a 1D array.

- We can use reshape(-1) to do this.

In [73]:
#Convert the array into a 1D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


> Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

In [74]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(6)
print(newarr)

[1 2 3 4 5 6]
